apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-service-secrets
  namespace: ecommerce
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend  # or aws-backend
  target:
    name: auth-secrets
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: ecommerce/auth/jwt
        property: secret
    - secretKey: db-password
      remoteRef:
        key: ecommerce/auth/database
        property: password
