apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: payment-service-secrets
  namespace: ecommerce
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-backend
  target:
    name: payment-secrets
    creationPolicy: Owner
  data:
    - secretKey: stripe-secret-key
      remoteRef:
        key: ecommerce/payment/stripe
        property: secret-key
    - secretKey: stripe-webhook-secret
      remoteRef:
        key: ecommerce/payment/stripe
        property: webhook-secret
