external-secrets:
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/external-secrets-role"

  vault:
    enabled: true
    authMethod: kubernetes
    role: external-secrets
    namespace: external-secrets

  aws:
    region: us-east-1
    role: external-secrets-role
