global:
  environment: dev
  domain: dev.ecommerce.com

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

monitoring:
  enabled: true
  retention: 5d

services:
  frontend:
    replicas: 2
    image:
      tag: dev
  auth:
    replicas: 2
    image:
      tag: dev
  catalog:
    replicas: 2
    image:
      tag: dev
  orders:
    replicas: 2
    image:
      tag: dev
  payment:
    replicas: 2
    image:
      tag: dev
