global:
  licenseKey: ${NEWRELIC_LICENSE_KEY}
  cluster: ${CLUSTER_NAME}

newrelic-infrastructure:
  enabled: true
  privileged: true
  
  integrations:
    nri-kubernetes:
      enabled: true
    nri-kube-events:
      enabled: true
    nri-prometheus:
      enabled: true
    nri-metadata-injection:
      enabled: true

nri-prometheus:
  enabled: true
  
  config:
    kubernetes:
      interval: "30s"

nri-kubernetes:
  enabled: true
  
  verboseLog: false
  
  privileged: true

ksm:
  enabled: true
