clusterName: "ecommerce-logs"
nodeGroup: "master"

replicas: 3

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

volumeClaimTemplate:
  resources:
    requests:
      storage: 30Gi

esJavaOpts: "-Xmx1g -Xms1g"

networkPolicy:
  enabled: true
