elasticsearchHosts: "http://elasticsearch-master:9200"

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: kibana.ecommerce.com
      paths:
        - path: /
  tls:
    - secretName: kibana-tls
      hosts:
        - kibana.ecommerce.com
